#!/usr/bin/env ruby
# frozen_string_literal: true

version, arm_sha, intel_sha = ARGV

if [version, arm_sha, intel_sha].any? { |value| value.nil? || value.empty? }
  abort "Usage: script/write_cask VERSION ARM_SHA256 INTEL_SHA256"
end

File.write(
  "Casks/appsignal-cli.rb",
  <<~RUBY
    cask "appsignal-cli" do
      arch arm: "aarch64", intel: "x86_64"

      version "#{version}"
      sha256 arm: "#{arm_sha}",
             intel: "#{intel_sha}"

      url "https://github.com/appsignal/homebrew-appsignal-cli/releases/download/v\#{version}/\#{arch}-apple-darwin.tar.gz",
          verified: "github.com/appsignal/homebrew-appsignal-cli/"
      name "appsignal-cli"
      desc "CLI for interacting with AppSignal"
      homepage "https://github.com/appsignal/homebrew-appsignal-cli"

      livecheck do
        url :url
        strategy :github_latest
      end

      binary "appsignal-cli"
    end
  RUBY
)
