#!/usr/bin/env ruby
# frozen_string_literal: true

version, macos_arm_sha, macos_intel_sha, linux_arm_sha, linux_intel_sha = ARGV

if [version, macos_arm_sha, macos_intel_sha, linux_arm_sha, linux_intel_sha].any? { |value| value.nil? || value.empty? }
  abort "Usage: script/write_formula VERSION MACOS_ARM_SHA256 MACOS_INTEL_SHA256 LINUX_ARM_SHA256 LINUX_INTEL_SHA256"
end

File.write(
  "Formula/appsignal-cli.rb",
  <<~RUBY
    class AppsignalCli < Formula
      desc "CLI for interacting with AppSignal"
      homepage "https://github.com/appsignal/appsignal-cli"
      version "#{version}"

      on_macos do
        on_arm do
          url "https://github.com/appsignal/appsignal-cli/releases/download/v\#{version}/aarch64-apple-darwin.tar.gz"
          sha256 "#{macos_arm_sha}"
        end

        on_intel do
          url "https://github.com/appsignal/appsignal-cli/releases/download/v\#{version}/x86_64-apple-darwin.tar.gz"
          sha256 "#{macos_intel_sha}"
        end
      end

      on_linux do
        on_arm do
          url "https://github.com/appsignal/appsignal-cli/releases/download/v\#{version}/aarch64-unknown-linux-gnu.tar.gz"
          sha256 "#{linux_arm_sha}"
        end

        on_intel do
          url "https://github.com/appsignal/appsignal-cli/releases/download/v\#{version}/x86_64-unknown-linux-gnu.tar.gz"
          sha256 "#{linux_intel_sha}"
        end
      end

      livecheck do
        url :stable
        strategy :github_latest
      end

      def install
        bin.install "appsignal-cli"
      end

      test do
        assert_match version.to_s, shell_output("\#{bin}/appsignal-cli --version")
      end
    end
  RUBY
)
